apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: alexandergc/auth
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "5000"
            - name: DB_USER
              value: root
            - name: DB_HOST
              value: auth-postgres-srv
            - name: DB_NAME
              value: auth-db
            - name: DB_PASSWORD
              value: password
            - name: DB_PORT
              value: "5432"
            - name: TOKEN
              value: my-secret-token
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  ports:
    - name: auth
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: auth
