apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  template:
    metadata:
      labels:
        app: auth-postgres
    spec:
      containers:
        - name: auth-postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: auth-db
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: auth-postgres-srv
spec:
  type: NodePort
  ports:
    - name: auth-postgres
      protocol: TCP
      nodePort: 30001
      port: 5432
      targetPort: 5432
  selector:
    app: auth-postgres
