name: users

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - "users/**"
  push:
    branches: [main]
    paths:
      - "users/**"

jobs:
  avoid_reduncy:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  test:
    if: ${{ github.event_name == 'pull_request' }}
    needs: [avoid_reduncy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        run: echo "Running tests" 
      - name: Showing paths
        run: cd users && ls
      #  run: cd users && npm run test 

  #build:
  #  if: ${{ github.event_name == 'pull_request' }}
  #  needs: [test]
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #    - name: Install dependencies
  #      run: cd users && npm install
  #    - name: Run Test
  #      run: cd users && npm run test

  build_and_push:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Showing paths
        run: ls

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t alexandergc/users:latest ./users

      - name: Push Docker Image
        run: docker push alexandergc/users:latest
        
  deploy_aws:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    #needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS
        run: echo "Starting deployment to AWS"

